### ISSUE TITLE
libffi-devel and openssl-devel missing

### ISSUE THREAD

**Issue by vex21** [RedHatQE/rhui3-automation#15] opened 2016-06-01 13:54 UTC
The ansible installation of test suite fails because a couple of -devel packages are missing. 

- libffi-devel
- openssl-devel

Having installed those two manually, I was able to complete the ansible run.

**Comment by alexxa** [comment] 2016-06-06 13:09
@vex21 Please confirm that it's applicable to NFS setup only. I can't reproduce it if Gluster.

**Comment by alexxa** [comment] 2016-06-28 12:57
QA note: check if applicable to RHEL7 NFS.

Error is on RHEL6.8 NFS confirmed

**Comment by alexxa** [comment] 2016-08-17 14:47
Fixed in commit 5515c80

**Closed by alexxa** 2016-08-17 14:47 UTC
Labels: bug
